const MODULOS_BASE = [
  {
    slug: "dashboard-geral",
    nome: "Dashboard Geral",
    categoria: "Core",
    descricao: "Painel consolidado com os principais indicadores operacionais.",
    icone: "LayoutDashboard",
    ordem: 1,
  },
  {
    slug: "processos-gerais",
    nome: "Gestão de Processos",
    categoria: "Core",
    descricao: "CRUD completo de processos, timeline e controle de prazos.",
    icone: "Briefcase",
    ordem: 2,
  },
  {
    slug: "clientes-gerais",
    nome: "Gestão de Clientes",
    categoria: "Core",
    descricao: "Cadastro, histórico e relacionamento com clientes.",
    icone: "Users",
    ordem: 3,
  },
  {
    slug: "agenda-compromissos",
    nome: "Agenda & Calendário",
    categoria: "Produtividade",
    descricao: "Agenda compartilhada com sincronização externa.",
    icone: "CalendarDays",
    ordem: 4,
  },
  {
    slug: "documentos-gerais",
    nome: "Documentos & Modelos",
    categoria: "Produtividade",
    descricao: "Gerenciamento de arquivos, versões e modelos padrão.",
    icone: "FileText",
    ordem: 5,
  },
  {
    slug: "tarefas-kanban",
    nome: "Tarefas & Kanban",
    categoria: "Produtividade",
    descricao: "Quadro Kanban, checklists e automações simples.",
    icone: "KanbanSquare",
    ordem: 6,
  },
  {
    slug: "relatorios-basicos",
    nome: "Relatórios Básicos",
    categoria: "Core",
    descricao: "Exportação de relatórios operacionais essenciais.",
    icone: "BarChart2",
    ordem: 7,
  },
  {
    slug: "gestao-equipe",
    nome: "Gestão de Equipe",
    categoria: "Core",
    descricao: "Cargos, permissões e convites para membros da equipe.",
    icone: "UserCog",
    ordem: 8,
  },
  {
    slug: "permissoes-avancadas",
    nome: "Permissões Granulares",
    categoria: "Core",
    descricao: "Controle avançado de acesso por rota e funcionalidade.",
    icone: "Shield",
    ordem: 9,
  },
  {
    slug: "contratos-honorarios",
    nome: "Contratos & Honorários",
    categoria: "Financeiro",
    descricao: "Gestão de contratos, modelos e honorários advocatícios.",
    icone: "ClipboardSignature",
    ordem: 10,
  },
  {
    slug: "financeiro-completo",
    nome: "Financeiro & Cobranças",
    categoria: "Financeiro",
    descricao: "Controle financeiro, faturas, conciliação e fluxo de caixa.",
    icone: "Wallet",
    ordem: 11,
  },
  {
    slug: "comissoes-advogados",
    nome: "Comissões de Advogados",
    categoria: "Financeiro",
    descricao: "Distribuição automática de comissões e repasses.",
    icone: "Percent",
    ordem: 12,
  },
  {
    slug: "modelos-documentos",
    nome: "Modelos Inteligentes",
    categoria: "Produtividade",
    descricao: "Geração automatizada de documentos via templates.",
    icone: "FileCode",
    ordem: 13,
  },
  {
    slug: "integracoes-externas",
    nome: "Integrações Externas",
    categoria: "Integracoes",
    descricao: "Catálogo de integrações (Asaas, ClickSign, Google, etc).",
    icone: "Puzzle",
    ordem: 14,
  },
  {
    slug: "notificacoes-avancadas",
    nome: "Notificações Avançadas",
    categoria: "Produtividade",
    descricao: "Central de notificações multicanal e alertas proativos.",
    icone: "BellRing",
    ordem: 15,
  },
  {
    slug: "assinaturas-digitais",
    nome: "Assinaturas Digitais",
    categoria: "Produtividade",
    descricao: "Fluxo de assinatura eletrônica integrado.",
    icone: "PenTool",
    ordem: 16,
  },
  {
    slug: "automacoes-fluxos",
    nome: "Automações & Fluxos",
    categoria: "Produtividade",
    descricao: "Regras automatizadas e gatilhos entre módulos.",
    icone: "Workflow",
    ordem: 17,
  },
  {
    slug: "analytics-avancado",
    nome: "Analytics & BI",
    categoria: "Inteligencia",
    descricao: "Dashboards avançados e indicadores personalizados.",
    icone: "LineChart",
    ordem: 18,
  },
  {
    slug: "ia-juridica",
    nome: "IA Jurídica",
    categoria: "Inteligencia",
    descricao: "Assistente jurídico, geração de peças e análises com IA.",
    icone: "Sparkles",
    ordem: 19,
  },
  {
    slug: "marketplace-integracoes",
    nome: "Marketplace de Soluções",
    categoria: "Integracoes",
    descricao: "Curadoria de aplicações e serviços complementares.",
    icone: "Store",
    ordem: 20,
  },
  {
    slug: "api-external",
    nome: "API & Webhooks",
    categoria: "Integracoes",
    descricao: "Acesso programático e webhooks para integrações customizadas.",
    icone: "Server",
    ordem: 21,
  },
  {
    slug: "atendimento-omnicanal",
    nome: "Atendimento Omnicanal",
    categoria: "Produtividade",
    descricao: "Central de atendimento integrada (WhatsApp, Email, Chat).",
    icone: "MessagesSquare",
    ordem: 22,
  },
  {
    slug: "laboratorio-recursos",
    nome: "Laboratório Magic",
    categoria: "Inteligencia",
    descricao: "Acesso antecipado a features beta e experimentos.",
    icone: "FlaskConical",
    ordem: 23,
  },
];

module.exports = async function seedModulos(prisma) {
  console.log("🧩 Criando catálogo de módulos do sistema...");

  for (const modulo of MODULOS_BASE) {
    const registro = await prisma.modulo.upsert({
      where: { slug: modulo.slug },
      update: {
        nome: modulo.nome,
        descricao: modulo.descricao,
        categoria: modulo.categoria,
        icone: modulo.icone,
        ordem: modulo.ordem,
        ativo: true,
        updatedAt: new Date(),
      },
      create: {
        ...modulo,
        ativo: true,
      },
    });

    console.log(`   • ${registro.nome} (${registro.slug})`);
  }

  console.log("✅ Catálogo de módulos atualizado!");
};

module.exports.MODULOS_BASE = MODULOS_BASE;
